name: Development Task
description: Tasks for enhancing current code, or adding minor things (not features)
title: "[Task]: "
body:
  - type: markdown
    attributes:
      value: |
        Describe task here.
  - type: input
    id: version
    attributes:
      label: Version of OpenTTD this task is to be implemented.
      description: Fill in below in what version of OpenTTD you propose to do this task.
      placeholder: ex. 1.11.2, Windows 10
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe new task.
      placeholder: |
        Replace tabs with spaces everywhere.
    validations:
      required: true
  - type: textarea
    id: implementation-description
    attributes:
      label: Implementation description
      description: Describe how do you think it might be implemented.
      placeholder: |
        1. We could use sed.
        2. Profit.
    validations:
      required: false
