name: Release

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Ref to build (for Pull Requests, use refs/pull/NNN/head)'
        required: true
  repository_dispatch:
    # client_payload should be the same as the inputs for workflow_dispatch.
    types:
    - Build*
  release:
    types:
    - published

jobs:
  source:
    name: Source

    uses: ./.github/workflows/release-source.yml
    secrets: inherit

  docs:
    name: Docs
    needs: source

    uses: ./.github/workflows/release-docs.yml
    secrets: inherit

    with:
      version: ${{ needs.source.outputs.version }}

  # Temporary disabled
  # emscripten:
  #   name: Emscripten
  #   needs: source

  #   uses: ./.github/workflows/release-emscripten.yml
  #   secrets: inherit

  linux:
    name: Linux (Generic)
    needs: source

    uses: ./.github/workflows/release-linux.yml
    secrets: inherit

  linux_random_debug:
      name: Linux Random Debug (Generic)
      needs: source

      uses: ./.github/workflows/release-linux-random-debug.yml
      secrets: inherit

  macos:
    name: MacOS
    needs: source

    uses: ./.github/workflows/release-macos.yml
    secrets: inherit

  macos_random_debug:
      name: MacOS Random Debug
      needs: source

      uses: ./.github/workflows/release-macos-random-debug.yml
      secrets: inherit

  windows:
    name: Windows
    needs: source

    uses: ./.github/workflows/release-windows.yml
    secrets: inherit

    with:
      is_tag: ${{ needs.source.outputs.is_tag }}

  windows_random_debug:
    name: Windows Random Debug
    needs: source

    uses: ./.github/workflows/release-windows-random-debug.yml
    secrets: inherit

    with:
      is_tag: ${{ needs.source.outputs.is_tag }}

  windows-store:
    name: Windows Store
    needs:
    - source
    - windows

    if: needs.source.outputs.is_tag == 'true'

    uses: ./.github/workflows/release-windows-store.yml
    secrets: inherit

    with:
      version: ${{ needs.source.outputs.version }}
